### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [Len-Stevens/Python-Antivirus#1]
I see you have no LICENSE file for this project.  The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by bigcadillack** [comment]
I am only using this as a step in my Cyber course, this is just a private test / lab grade and honestly I have no clue about what you are requesting - I am sure we will learn about this later on... In other words I am totally new to this process, just following the steps in the assignment.

**Comment by dave9123** [comment]
LICENSE is how people can do toward this repository like use it and make a comercial or open source project and etc

**Comment by MandiYang** [comment]
The project has added a LICENSE (GPL-3.0), now the issue can be closed.
