### ISSUE TITLE
Tile

### ISSUE THREAD

**Issue by lllJustVlll** [Len-Stevens/Python-Antivirus#16]
Could you explain to me how to import these modules or attach the versions of the modules that the program will work with?
import file name from file
from PyQt5 import QtCore, QtGui, QtWidgets
from virustotal_python import Virustotal
import configuration parser
import web browser
import requests
import hash library
system import
OS import

**Comment by raphael069** [comment]
Sure, create a file called req.txt and copy the text below in it and then save and run it with `pip install -r (path to the file)/req.txt`:
```
PyQt5
requests== 2.28.1
configparser
virustotal_python
```
I think the rest of the packages are already pre installed.

**Comment by lllJustVlll** [comment]
Where to download pip install -r   ?
