### ISSUE TITLE
Can't scan file in Linux

### ISSUE THREAD

**Issue by SkyFizh** [Len-Stevens/Python-Antivirus#28]
Ive tried running the program in Windows and Linux. Both os was able to run the program. My problem is when i tried selecting a file to be scan in linux, it gives me the error 'No file selected or Program Has no permission to file' . Ive tried giving extra permission to said file and antivirus program. Btw the file i asked to scan was the README.md file.

**Comment by SkyFizh** [comment]
I found solution, i edited a first few line (25-27).. However this line should work on linux only. I just found out that linux and windows uses different backslashes to navigate files. 


To this: 
SHA256_HASHES_pack1 = (current_dir + '//hard_signatures//SHA256-Hashes_pack1.txt')
SHA256_HASHES_pack2 = (current_dir + '//hard_signatures//SHA256-Hashes_pack2.txt')
SHA256_HASHES_pack3 = (current_dir + '//hard_signatures//SHA256-Hashes_pack3.txt')

Perhaps, this antivirus can be improved with if else statements on figuring operating system? Because as far as i concern the original source code does not works on linux.

**Comment by raphael069** [comment]
I think I already fixed this issue in my fork, check it out it also has a few more improvements!
