### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Decation2** [Len-Stevens/Python-Antivirus#4]
Im downloaded program and the program dont want to launch

**Comment by Len-Stevens** [comment]
Could you provide your error message?

**Comment by cookie0o** [comment]
Can you tell me what Python version do you use since some may have issues with some libs imported

**Comment by Decation2** [comment]
im use the latest python version

**Comment by MandiYang** [comment]
> im use the latest python version

Any error message to identify the problem????
